### PR TITLE
Replace deprecated logging.warn with logging.warning

### PR DESCRIPTION
**Pull request by Mulan-94**
- This was done to remove the extra deprecation warning.

### CODE REVIEW

**Comment by sjperkins** [comment]
Thanks for the contribution @Mulan-94.

Could you update the HISTORY.rst? Needs something like a:

```rst
0.10.0 (YYYY-MM-DD)
----------------------------

* fill me in.
```

**Comment by Mulan-94** [comment]
Updated

**Comment by sjperkins** [comment]
Sorry, I got the restructured text underlining wrong. Length needs to match up with the header text directly above it.

```rst
0.10.0 (YYYY-MM-DD)
-------------------
```

**Comment by sjperkins** [comment]
Thanks for the contribution Lexy!

**Pull request merged**
